aifrd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _



urlpatterns = [
    # django rest api
   
    path('api-auth/', include('rest_framework.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('what_we_are_doing/', include('what_we_are_doing.urls', namespace='what_we_are_doing')),
    path('about/', include('about.urls', namespace='about')),
    path('get_involved/', include('get_involved.urls', namespace='get_involved')),
    path('media/', include('mediapage.urls', namespace='media')),


)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_url = None
admin.site.site_header = 'HuminImp Administration'

get_involved/urls.py
from django.urls import path
from . import views

app_name = 'get_involved'

urlpatterns = [
    path('', views.get_involved, name='get_involved'),
    path('volunteer/', views.volunteer, name='volunteer'),

    path('donate/', views.donate, name='donate'),
    path('careerlist/', views.career_list, name='career_list'),
    path('api/careerForm/<str:carrer_name>', views.careerForm, name='careerForm'),

    # path('careerdetail/<int:id>', views.career_detail, name='career_detail'),
    # path('careerdetail/<int:career_id>', views.career_detail, name='career_detail'),
    path('careerdetail/<int:id>/', views.career_detail, name='career_detail'),
    # path('themes/<int:theme_id>/', views.theme_detail, name='themes_details'),

]

home/urls.py
from django.urls import include, path

from . import views
from . import api


app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
 
    path('contact', views.contact, name='contact'),

]

mediapage/urls.py
from django.urls import path
from . import views

app_name = 'media'

urlpatterns = [
    path('', views.media_list, name='media'),
  path("media_filter/", views.media_filter, name="media_filter"),

    path("media/<int:id>/", views.media_detail, name="media_detail"),

]

get_involved/views.py
from typing import List
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from .models import GetInvolved,Volunteer, Donate,CareerDetail,CareerList
from django.core.paginator import Paginator
from mediapage.models import MediaDetail 
from django.urls import reverse
from django.http import HttpRequest
from .serializers import GetInvolvedSerializer,VolunteerSerializer,CareerListSerializer, DonateSerializer,CareerDetailSerializer
from .filters import CareerDetailFilter
from django.core.mail import send_mail,  EmailMessage


# Create your views here.
def get_involved(request):
    """Renders the create get_involved page."""
    assert isinstance(request, HttpRequest)
    queryset = GetInvolved.objects.all()
    serializer_class = GetInvolvedSerializer(queryset, many=True)
    media = MediaDetail.objects.all()

    # Show many contacts per page for stories
    paginator_media = Paginator(media, 10000000000000000)
    page_number_media = request.GET.get('page')
    page_obj_media = paginator_media.get_page(page_number_media)

    return render(request, 'get-involved.html',
                  {
                      'data': serializer_class.data,
        'media' : page_obj_media
                  }
                  )

def volunteer(request):
    """Renders the create volunteer page."""
    assert isinstance(request, HttpRequest)
    queryset = Volunteer.objects.all()
    serializer_class = VolunteerSerializer(queryset, many=True)
    media = MediaDetail.objects.all()

    # Show many contacts per page for stories
    paginator_media = Paginator(media, 10000000000000000)
    page_number_media = request.GET.get('page')
    page_obj_media = paginator_media.get_page(page_number_media)

    return render(request, 'volunteers.html',
                  {
                      'data': serializer_class.data,
        'media' : page_obj_media
                  }
                  )


def volunteerForm(request):
    if request.method == 'POST':
        print("hello")
        name = request.POST.get('full_name')
        gender = request.POST.get('gender')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        region = request.POST.get('region')
        address = request.POST.get('address')
        upload_cv = request.FILES.get('upload_cv')
        English = request.POST.get('English')
        Arabic = request.POST.get('Arabic')
        Kurdish = request.POST.get('Kurdish')
        languages = {"English": English,
        "Arabic":Arabic,
        "Kurdish":Kurdish
        }
        cover_letter = request.POST.get('cover_letter')
        # print(select_language)
        select_language = []

        for language in languages:
            print(language)
            if languages[language] != None:
                select_language.append(language)
        data = {
            'name': name,
            'gender' : gender,
            'email' : email,
            'phone' : phone,
            'region' : region,

            'address': address,
            'upload_cv' : upload_cv,
            'select_language' : select_language,
            'cover_letter' : cover_letter,
        }
        print(data)
        print("hello")
        message = ''' 
        New applicant :{}
        From: {}
        Phone: {}
        Region: {}
        Gender: {}
        Address:{}
        CV: {}
        Language:{}
        Cover_letter: {}


        '''.format(data['name'], data['email'], data['phone'], data['region'], data['gender'], data['address'], data['upload_cv'], data['select_language'], data['cover_letter'])

        if name and gender and email  and phone and  region  and  address and   upload_cv  and cover_letter:

            email = EmailMessage(
                              data['name'],    
                              message,
                              'Info@ashuor.org', ['Info@ashuor.org'],)
                          
            if request.FILES:
                            uploaded_file = request.FILES['upload_cv'] # file is the name value which you have provided in form for file field
                            email.attach(uploaded_file.name, uploaded_file.read(), uploaded_file.content_type)
                            email.send()
            #     send_mail(data['carrer_name'], message, from_email= 'info@ashuor.org',recipient_list= ['hr@aifrd.org'],  fail_silently=False)
            #     send_mail.attach(message. attach.read(), )
            #     send_mail.send()
            # except  Exception as error:
            #     return HttpResponse('Invalid header found.')
    return render(request, 'volunteer.html', {
    
        'media' : page_obj_media
    })
def donate(request):
    """Renders the create volunteer page."""
    assert isinstance(request, HttpRequest)
    queryset = Donate.objects.all()
    serializer_class = DonateSerializer(queryset, many=True)
    media = MediaDetail.objects.all()

    # Show many contacts per page for stories
    paginator_media = Paginator(media, 10000000000000000)
    page_number_media = request.GET.get('page')
    page_obj_media = paginator_media.get_page(page_number_media)

    return render(request, 'donate.html',
                  {
                      'data': serializer_class.data,
        'media' : page_obj_media
                  }
                  )

def career_list(request):
    career_list = CareerDetail.objects.all()
    assert isinstance(request, HttpRequest)
    queryset = CareerList.objects.all()
    media = MediaDetail.objects.all()

    # Show many contacts per page for stories
    paginator_media = Paginator(media, 10000000000000000)
    page_number_media = request.GET.get('page')
    page_obj_media = paginator_media.get_page(page_number_media)
    # filters
    myfilter = CareerDetailFilter(request.GET, queryset=career_list)
    career_list = myfilter.qs

    # Show many contacts per page.
    paginator = Paginator(career_list, 10000000000000000)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if career_list:
        context = {'careers': page_obj, 'myfilter': myfilter,
        'media' : page_obj_media,
        'img_bg': queryset}  # template name

    else:
        context = {'message': "There are no jobs available at the moment."}
    return render(request, 'career.html', context)


def career_detail(request, id):
    career_detail = CareerDetail.objects.get(id=id)
    queryset = CareerList.objects.all()
    serializer_class = CareerListSerializer(queryset, many=True)
    media = MediaDetail.objects.all()

    # Show many contacts per page for stories
    paginator_media = Paginator(media, 10000000000000000)
    page_number_media = request.GET.get('page')
    page_obj_media = paginator_media.get_page(page_number_media)

    context = {'item': career_detail, 'data': serializer_class.data,   'media' : page_obj_media}
    return render(request, 'careers-details.html', context)
    
def careerForm(request,carrer_name):
    media = MediaDetail.objects.all()

    # Show many contacts per page for stories
    paginator_media = Paginator(media, 10000000000000000)
    page_number_media = request.GET.get('page')
    page_obj_media = paginator_media.get_page(page_number_media)
    if request.method == 'POST':
        print("hello")
        name = request.POST.get('full_name')
        # career_name = request.POST.get('career_name')
        gender = request.POST.get('gender')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        region = request.POST.get('region')
        address = request.POST.get('address')
        upload_cv = request.FILES.get('upload_cv')
        English = request.POST.get('English')
        Arabic = request.POST.get('Arabic')
        Kurdish = request.POST.get('Kurdish')
        languages = {"English": English,
        "Arabic":Arabic,
        "Kurdish":Kurdish
        }
        cover_letter = request.POST.get('cover_letter')
        # print(select_language)
        select_language = []

        for language in languages:
            print(language)
            if languages[language] != None:
                select_language.append(language)
        data = {
            'name': name,
            'carrer_name':carrer_name,
            'gender' : gender,
            'email' : email,
            'phone' : phone,
            'region' : region,

            'address': address,
            'upload_cv' : upload_cv,
            'select_language' : select_language,
            'cover_letter' : cover_letter,
        }
        print(data)
        message = ''' 
        New applicant :{}
        From: {}
        Career Name : {}
        Phone: {}
        Region: {}
        Gender: {}
        Address:{}
        CV: {}
        Language:{}
        Cover_letter: {}


        '''.format(data['name'], data['email'],data['carrer_name'], data['phone'], data['region'], data['gender'], data['address'], data['upload_cv'], data['select_language'], data['cover_letter'])

        if name and gender and email and carrer_name and phone and  region and address and   upload_cv  and cover_letter:
         
            email = EmailMessage(
                              data['carrer_name'],    
                              message,
                              'Info@ashuor.org', ['Info@ashuor.org'],)
                          
            if request.FILES:
                            uploaded_file = request.FILES['upload_cv'] # file is the name value which you have provided in form for file field
                            email.attach(uploaded_file.name, uploaded_file.read(), uploaded_file.content_type)
                            email.send()
            #     send_mail(data['carrer_name'], message, from_email= 'representative@aifrd.org',recipient_list= ['hr@aifrd.org'],  fail_silently=False)
            #     send_mail.attach(message. attach.read(), )
            #     send_mail.send()
            # except  Exception as error:

get_involved/templates/career.html
{% extends 'base.html' %}
{% block body %}
{% load static %}

{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
        <!-- Page Title Section Start -->
        <div class="page-title-section section">
            <div class="page-title">
           
            </div>
            <div class="page-breadcrumb">
                <div class="container">
                    <ul class="breadcrumb">
                        <li><a href="{% url 'home:index' %}">{% trans "Home" %}</a></li>
                        <li><a href="{% url 'get_involved:get_involved' %}">{% trans "Get involved" %}</a></li>
        

                        <li class="current">{% trans "Careers" %} </li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Page Title Section End -->
        <!-- Blog Section Start -->
        <div class="section  fix">
            <div class="container">
                <div class="row max-mb-n50">

                    <div class="col-lg-12 col-12 order-lg-1 max-mb-50">
                        <!-- Blog Wrapper Start -->
                        <div class="row row-cols-1 g-0">

                            <!-- Blog Start -->
                            <div class=" col" data-aos="fade-up">


                                <!-- Page Banner Section Start -->
                                <div class="page-banner-section section overlay section-padding"
                                    data-bg-image="{% static 'home/images/people.jpg' %}">
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="page-banner-title ashor-banner-title">
                                                    <h1 class="title" style="padding: 50px;">
                                                    </h1>
                                                </div>


                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Page Banner Section End -->



                            </div>
                        </div>
                    </div>
                    <!-- Blog End -->


                </div>
                <!-- Blog Wrapper End -->
            </div>


        </div>
    </div>


    <!-- Testimonial Section Start -->
    <div class="section section-padding fix">
        <div class="container">


            <!--Testimonial Slider Start -->
            <div class="row">
                <div class="offset-lg-2 col-lg-8">
                <div class="page-title-section section section-padding-top-0" style="padding-top: 0px;">
                    <div class="page-breadcrumb">
                        <div class="container">
                            <ul class="breadcrumb">

                                <li> {% trans "jobs" %} : 4</li>
                                <li class="current"> {% trans "Locations" %} : 2 </li>
                                <li class="current"> {% trans "Categories" %} : 2</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
               <div class="row">
                {% for item in careers %}

                <div class="offset-lg-2 col-lg-8">
                    <div class="testimonial-two">
                        <div class="author-info">
                            <a href="{% url 'get_involved:career_detail' id=item.id %}">
                                <div class="cite">

                                    <h6 class="name">{% if LANGUAGE_CODE == 'en' %} {{item.career_name}}
                                        {% elif LANGUAGE_CODE == 'ar' %} {{item.career_name_ar}}
                                        {% elif LANGUAGE_CODE == 'de' %} {{item.career_name_dr}} {% endif %} </h6>
                                    <span class="position">{% if LANGUAGE_CODE == 'en' %} {{item.career_employee_type}}
                                        {% elif LANGUAGE_CODE == 'ar' %} {{item.career_employee_type_ar}}
                                        {% elif LANGUAGE_CODE == 'de' %} {{item.career_employee_type_dr}} {% endif %} . {% if LANGUAGE_CODE == 'en' %} {{item.job_type}}
                                        {% elif LANGUAGE_CODE == 'ar' %} {{item.job_type_ar}} {% endif %} {% if LANGUAGE_CODE == 'en' %} {{item.location}}
                                        {% elif LANGUAGE_CODE == 'ar' %} {{item.location_ar}}
                                        {% elif LANGUAGE_CODE == 'de' %} {{item.location_dr}} {% endif %}</span>
                                </div>
                            </a>
                        </div>
                        <div class="content">
                            <p>{% if LANGUAGE_CODE == 'en' %} {{item.career_desc}}
                                {% elif LANGUAGE_CODE == 'ar' %} {{item.career_desc_ar}} 
                                {% elif LANGUAGE_CODE == 'de' %} {{item.career_desc_dr}}{% endif %}

                            </p>
                        </div>
                    </div>
                </div>
                {% endfor %}

               </div>


            </div>






            <!--Testimonial Slider End -->

        </div>
    </div>
  
    {% endblock body %}

get_involved/templates/careers-details.html
{% extends 'base.html' %}
{% block body %}
{% load static %}

{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
        <!-- Page Title Section Start -->
        <div class="page-title-section section">
            <div class="page-title">

            </div>
            <div class="page-breadcrumb">
                <div class="container">
                    <ul class="breadcrumb">
                        <li><a href="{% url 'home:index' %}">{% trans "Home" %}</a></li>
                        <li><a href="{% url 'get_involved:get_involved' %}">{% trans "Get involved" %}</a></li>
        
                        <li><a href="{% url 'get_involved:career_list' %}">{% trans "Careers" %}</a></li>

                    </ul>
                </div>
            </div>
        </div>

        <div class="section  fix">
            <div class="container">
                <div class="row max-mb-n50">

                    <div class="col-lg-12 col-12 order-lg-1 max-mb-50">
                        <!-- Blog Wrapper Start -->
                        <div class="row row-cols-1 g-0">

                            <!-- Blog Start -->
                            <div class=" col" data-aos="fade-up">


                                <!-- Page Banner Section Start -->
                                <div class="page-banner-section section overlay section-padding"
                                    data-bg-image="./assets/images/page-banner/course-bg.jpg">
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="page-banner-title ashor-banner-title">
                                                    <h1 class="title"> {% if LANGUAGE_CODE == 'en' %} {{item.career_name}}
                                                        {% elif LANGUAGE_CODE == 'ar' %} {{item.career_name_ar}} 
                                                        {% elif LANGUAGE_CODE == 'de' %} {{item.career_name_dr}}{% endif %}
                                                   

                                                    </h1>
                                                    <h4 class="sub-title" style="color: white;">  {% if LANGUAGE_CODE == 'en' %} {{item.career_employee_type}}
                                                        {% elif LANGUAGE_CODE == 'ar' %} {{item.career_employee_type_ar}}  {% elif LANGUAGE_CODE == 'de' %} {{item.career_employee_type_dr}}{% endif %} . {% if LANGUAGE_CODE == 'en' %} {{item.job_type}}
                                                        {% elif LANGUAGE_CODE == 'ar' %} {{item.job_type_ar}}{% elif LANGUAGE_CODE == 'de' %} {{item.job_type_dr}} {% endif %} {% if LANGUAGE_CODE == 'en' %} {{item.location}}
                                                        {% elif LANGUAGE_CODE == 'ar' %} {{item.location_ar}}{% elif LANGUAGE_CODE == 'de' %} {{item.location_dr}} {% endif %}
                                                    </h4>
                                                </div>


                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Page Banner Section End -->



                            </div>
                        </div>
                    </div>
                    <!-- Blog End -->


                </div>
                <!-- Blog Wrapper End -->
            </div>


        </div>




        <div class="section section-padding-bottom" style="padding-top: 50px;">
            <div class="container">
                <div class="row max-mb-n50">

                    <div class="offset-lg-2 col-lg-8  order-lg-2 max-mb-50">
                        <div class="purchase-guide-wrapper">

                            <div class="content">
                                <h3 class="title">{% trans "Summary" %}</h3>

                                <p>{% if LANGUAGE_CODE == 'en' %} {{item.career_summary_text}}
                                    {% elif LANGUAGE_CODE == 'ar' %} {{item.career_summary_text_ar}} 
                                    {% elif LANGUAGE_CODE == 'de' %} {{item.career_summary_text_dr}}{% endif %}
                                </p>

                                <h3 class="title">DUTIES AND RESPONSIBILITIES
                                </h3>

                                <p>{% if LANGUAGE_CODE == 'en' %} {{item.career_duties_text}}
                                    {% elif LANGUAGE_CODE == 'ar' %} {{item.career_duties_text_ar}}
                                    {% elif LANGUAGE_CODE == 'de' %} {{item.career_duties_text_dr}} {% endif %}:</p>

                                <ul>
                                    <li>{% if LANGUAGE_CODE == 'en' %} {{item.duties_1}}
                                        {% elif LANGUAGE_CODE == 'ar' %} {{item.duties_1_ar}} 
                                        {% elif LANGUAGE_CODE == 'de' %} {{item.duties_1_dr}}{% endif %}
                                    </li>
                                    <li>{% if LANGUAGE_CODE == 'en' %} {{item.duties_2}}
                                        {% elif LANGUAGE_CODE == 'ar' %} {{item.duties_2_ar}}
                                        {% elif LANGUAGE_CODE == 'de' %} {{item.duties_2_dr}} {% endif %}
                                    </li>
                                    <li>{% if LANGUAGE_CODE == 'en' %} {{item.duties_3}}
                                        {% elif LANGUAGE_CODE == 'ar' %} {{item.duties_3_ar}}
                                        {% elif LANGUAGE_CODE == 'de' %} {{item.duties_3_dr}} {% endif %}
                                    </li>
                                    <li>{% if LANGUAGE_CODE == 'en' %} {{item.duties_4}}
                                        {% elif LANGUAGE_CODE == 'ar' %} {{item.duties_4_ar}}  {% elif LANGUAGE_CODE == 'de' %} {{item.duties_4_dr}} {% endif %}
                                    </li>
                                    <li>{% if LANGUAGE_CODE == 'en' %} {{item.duties_5}}
                                        {% elif LANGUAGE_CODE == 'ar' %} {{item.duties_5_ar}}
                                        {% elif LANGUAGE_CODE == 'de' %} {{item.duties_5_dr}} {% endif %}
                                    </li>

                                </ul>

                                <h3 class="title">{% trans "SKILLS" %}
                                </h3>
                                <ul>
                                    <li>{% if LANGUAGE_CODE == 'en' %} {{item.skill_1}}
                                        {% elif LANGUAGE_CODE == 'ar' %} {{item.skill_1_ar}} {% elif LANGUAGE_CODE == 'de' %} {{item.skill_1_dr}} {% endif %}
                                    </li>
                                    <li>{% if LANGUAGE_CODE == 'en' %} {{item.skill_2}}
                                        {% elif LANGUAGE_CODE == 'ar' %} {{item.skill_2_ar}}{% elif LANGUAGE_CODE == 'de' %} {{item.skill_2_dr}} {% endif %}
                                    </li>
                                 
                                    <li>{% if LANGUAGE_CODE == 'en' %} {{item.skill_3}}
                                        {% elif LANGUAGE_CODE == 'ar' %} {{item.skill_3_ar}}  {% elif LANGUAGE_CODE == 'de' %} {{item.skill_3_dr}}{% endif %}
                                    </li>
                                    <li>{% if LANGUAGE_CODE == 'en' %} {{item.skill_4}}
                                        {% elif LANGUAGE_CODE == 'ar' %} {{item.skill_4_ar}}{% elif LANGUAGE_CODE == 'de' %} {{item.skill_4_dr}} {% endif %}
                                    </li>

                                </ul>

                                <div class="col-12 text-center max-mb-30">
                                    <a href="{% url 'get_involved:careerForm' item %}"> <button
                                            class="btn btn-primary btn-hover-secondary btn-width-200 btn-height-60">{% trans "SUBMIT FOR THIS POSITION" %}</button></a>
                                </div>
                            </div>
                        </div>
                        <!-- Purchase Guide Wrapper End -->
                    </div>



                </div>
            </div>
        </div>
        <div class="about-section section" style="padding: 50px;">
            <div class="container">


                <div class="row">
                    <div class="col-12">
                        <div class="event-content">





                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="section section-padding-bottom" style="padding-top: 50px;">
            <div class="container">
    
                <!--  media Bar Start -->
                <div class="row justify-content-between align-items-center max-mb-20">
                    <div class="col-sm-auto col-12 max-mb-10">
                        <p class="result-count">{% trans "Latest Media" %}</p>
                    </div>
    
                </div>
                <!-- media Top Bar End -->
    
                <!-- media  Start -->
                <div class="row row-cols-xl-4 row-cols-lg-2 row-cols-md-2 row-cols-1 max-mb-n30">
                    {% for item in media  %}
                    {% if forloop.counter < 5 %} 
                    <div class="col max-mb-30">
                        <div class="media-6">
                            <div class="thumbnail">
                                <a class="image" href="{% url 'media:media_detail' item.id %}">
                                    <img src="{{item.media_image.url}}" height="350px" style="object-fit: cover;" alt="">
                                    <div class="media-overlay-bg"></div>
                                </a>
                            </div>
                            <div class="info">
                                <div class="media-caption-main">
                                    <a class="category" style="color: white;"> {% if LANGUAGE_CODE == 'en' %}{{ item.category.en_name }}
                                        {% elif LANGUAGE_CODE == 'ar' %} {{ item.category.ar_name }}
                                        {% elif LANGUAGE_CODE == 'de' %} {{ item.category.dr_name }}{% endif %}</a>
                                    <ul class="meta">
                                        <li><i class="far fa-map-marker-alt"></i> {% if LANGUAGE_CODE == 'en' %}{{ item.media_location }}
                                            {% elif LANGUAGE_CODE == 'ar' %} {{ item.media_location_ar }}
                                            {% elif LANGUAGE_CODE == 'de' %} {{ item.media_location_dr }}{% endif %}</li>
                                        <li><i class="far fa-calendar"></i>{{item.date|date:'d M o'}}</li>
                                    </ul>
                                    <h3 class="title"><a href="{% url 'media:media_detail' item.id %}"> {% if LANGUAGE_CODE == 'en' %}{{ item.media_name }}
                                        {% elif LANGUAGE_CODE == 'ar' %} {{ item.media_name_ar }}
                                        {% elif LANGUAGE_CODE == 'de' %} {{ item.media_name_dr }}{% endif %}</a></h3>
                                </div>
                                <div class="media-caption-collapse">
                                   
                                    <div class="desc">
                                        <p> {% if LANGUAGE_CODE == 'en' %}{{ item.media_desc1 }}
                                            {% elif LANGUAGE_CODE == 'ar' %} {{ item.media_desc1_ar }}
                                            {% elif LANGUAGE_CODE == 'de' %} {{ item.media_desc1_dr }}{% endif %}…</p>
                                    </div>
                                </div>
                            </div>
                        </div>
    
                    </div>
                 
                    {% endif %} {% endfor %}
    
    
                </div>
                <!-- media  End -->
    
    
                <div class="row max-mt-50">
                    <div class="col text-center">
                        <a href="{% url 'media:media' %}" class="btn btn-outline-primary load-more-btn">{% trans "Read More" %} <i
                                class="far fa-long-arrow-right ms-3"></i></a>
                    </div>
                </div>
    
            </div>
        </div>
        {% endblock body %}