about/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from . import views

app_name = 'about'

urlpatterns = [
    path('', views.about, name='about'),
        path('goals/', views.goals, name='goals'),
        path('history/', views.history, name='history'),
        path('vission_mission/', views.vission_mission, name='vission_mission'),
        path('partener_network/', views.partener_network, name='partener_network'),
        path('internal_system/', views.internal_system, name='internal_system'),
        path('where_we_work/', views.where_we_work, name='where_we_work'),
        path('grass_root/', views.grass_root, name='grass_root'),
        path('academics/', views.academics, name='academics'),
        path('capacity/', views.capacity, name='capacity'),
        path('methodology/', views.methodology, name='methodology'),
        path('roles/', views.roles, name='roles'),
        path('assesments/', views.assesments, name='assesments'),
        path('resources/', views.resources, name='resources'),
        path('polies/', views.polies, name='polies'),
        path('people/', views.people, name='people'),

        path('core_list/', views.core_list, name='core_list'),
        path('core_detail/<int:id>', views.core_detail, name='core_detail'),

   
]

aifrd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _



urlpatterns = [
    # django rest api
   
    path('api-auth/', include('rest_framework.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('what_we_are_doing/', include('what_we_are_doing.urls', namespace='what_we_are_doing')),
    path('about/', include('about.urls', namespace='about')),
    path('get_involved/', include('get_involved.urls', namespace='get_involved')),
    path('media/', include('mediapage.urls', namespace='media')),


)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_url = None
admin.site.site_header = 'HuminImp Administration'

home/urls.py
from django.urls import include, path

from . import views
from . import api


app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
 
    path('contact', views.contact, name='contact'),

]

mediapage/urls.py
from django.urls import path
from . import views

app_name = 'media'

urlpatterns = [
    path('', views.media_list, name='media'),
  path("media_filter/", views.media_filter, name="media_filter"),

    path("media/<int:id>/", views.media_detail, name="media_detail"),

]

about/views.py
from email.message import EmailMessage
from django.shortcuts import redirect, render
from django.http import HttpResponse
from rest_framework import generics, permissions
from mediapage.models import MediaDetail
from .models import About,Goal, Roles, People, Polies,Resources, Assesments, Academics,CoreBgImage,WhereWeWorkBackground, MethodologyList, GrassRoot,Capacity,Methodology, CapacityList, VisionMissionValue,WhereWeWork, InternalSystemList, Goal,PartenerLogo, PartenerNetwork, InternalSystem, GoalList, Core, History
from .serializers import AboutSerializer, PeopleSerializer,ResourcesSerializer, AssesmentsSerializer, PoliesSerializer, RolesSerializer, WhereWeWorkBackgroundSerializer,CoreBgImageSerializer,MethodologyListSerializer, GoalSerializer,MethodologySerialize, CapacityListSerializer, CapacitySerializer, AcademicsSerializer, GrassRootSerializer, WhereWeWorkSerializer, InternalSystemListSerializer, VisionMissionValueSerializer, PartenerNetworkSerializer, InternalSystemSerializer, GoalListSerializer, CoreSerializer, HistorySerializer
from django.http import HttpRequest
from rest_framework.renderers import JSONRenderer, TemplateHTMLRenderer
from django.core.paginator import Paginator
from django.utils.translation import get_language, activate

from django.core.mail import send_mail,  EmailMessage
# from .filters import CoreDetailFilter




renderer_classes = (JSONRenderer, TemplateHTMLRenderer,)



def about(request):
    """Renders the create about page."""
    assert isinstance(request, HttpRequest)
    queryset = About.objects.all()
    serializer_class = AboutSerializer(queryset, many=True)
    media = MediaDetail.objects.all()

    # Show many contacts per page for stories
    paginator_media = Paginator(media, 10000000000000000)
    page_number_media = request.GET.get('page')
    page_obj_media = paginator_media.get_page(page_number_media)

    return render(request, 'about.html',
                  {
                      'data': serializer_class.data,
        'media' : page_obj_media
                  }
                  )



def goals(request):
    """Renders the create goals page."""
    assert isinstance(request, HttpRequest)
    queryset = GoalList.objects.all()
    serializer_class = GoalListSerializer(queryset, many=True)
    queryset = Goal.objects.all()
    img = GoalSerializer(queryset, many=True)
    media = MediaDetail.objects.all()

    # Show many contacts per page for stories
    paginator_media = Paginator(media, 10000000000000000)
    page_number_media = request.GET.get('page')
    page_obj_media = paginator_media.get_page(page_number_media)

    return render(request, 'goals.html',
                  {
                      'goal': serializer_class.data,
                      'img': img.data,
        'media' : page_obj_media
                  }
                  )


def history(request):
    """Renders the create history page."""
    assert isinstance(request, HttpRequest)
    queryset = History.objects.all()
    serializer_class = HistorySerializer(queryset, many=True)
    media = MediaDetail.objects.all()

    # Show many contacts per page for stories
    paginator_media = Paginator(media, 10000000000000000)
    page_number_media = request.GET.get('page')
    page_obj_media = paginator_media.get_page(page_number_media)

    return render(request, 'history.html',
                  {
                      'history': serializer_class.data,
        'media' : page_obj_media
                  }
                  )

def roles(request):
    """Renders the create history page."""
    assert isinstance(request, HttpRequest)
    queryset = Roles.objects.all()
    serializer_class = RolesSerializer(queryset, many=True)
    media = MediaDetail.objects.all()

    # Show many contacts per page for stories
    paginator_media = Paginator(media, 10000000000000000)
    page_number_media = request.GET.get('page')
    page_obj_media = paginator_media.get_page(page_number_media)

    return render(request, 'role_responsiblities.html',
                  {
                      'data': serializer_class.data,
        'media' : page_obj_media
                  }
                  )

def people(request):
    """Renders the create history page."""
    assert isinstance(request, HttpRequest)
    queryset = People.objects.all()
    serializer_class = PeopleSerializer(queryset, many=True)
    media = MediaDetail.objects.all()

    # Show many contacts per page for stories
    paginator_media = Paginator(media, 10000000000000000)
    page_number_media = request.GET.get('page')
    page_obj_media = paginator_media.get_page(page_number_media)

    return render(request, 'people.html',
                  {
                      'data': serializer_class.data,
        'media' : page_obj_media
                  }
                  )


def resources(request):
    """Renders the create history page."""
    assert isinstance(request, HttpRequest)
    queryset = Resources.objects.all()
    serializer_class = ResourcesSerializer(queryset, many=True)
    media = MediaDetail.objects.all()

    # Show many contacts per page for stories
    paginator_media = Paginator(media, 10000000000000000)
    page_number_media = request.GET.get('page')
    page_obj_media = paginator_media.get_page(page_number_media)

    return render(request, 'resource_publication.html',
                  {
                      'data': serializer_class.data,
        'media' : page_obj_media
                  }
                  )


def polies(request):
    """Renders the create history page."""
    assert isinstance(request, HttpRequest)
    queryset = Polies.objects.all()
    serializer_class = PoliesSerializer(queryset, many=True)
    media = MediaDetail.objects.all()

    # Show many contacts per page for stories
    paginator_media = Paginator(media, 10000000000000000)
    page_number_media = request.GET.get('page')
    page_obj_media = paginator_media.get_page(page_number_media)

    return render(request, 'polies_stratigies.html',
                  {
                      'data': serializer_class.data,
        'media' : page_obj_media
                  }
                  )

def assesments(request):
    """Renders the create history page."""
    assert isinstance(request, HttpRequest)
    queryset = Assesments.objects.all()
    serializer_class = AssesmentsSerializer(queryset, many=True)
    media = MediaDetail.objects.all()

    # Show many contacts per page for stories
    paginator_media = Paginator(media, 10000000000000000)
    page_number_media = request.GET.get('page')
    page_obj_media = paginator_media.get_page(page_number_media)

    return render(request, 'assesment_analysis.html',
                  {
                      'data': serializer_class.data,
        'media' : page_obj_media
                  }
                  )
def vission_mission(request):
    """Renders the create history page."""
    assert isinstance(request, HttpRequest)
    queryset = VisionMissionValue.objects.all()
    serializer_class = VisionMissionValueSerializer(queryset, many=True)
    media = MediaDetail.objects.all()

    # Show many contacts per page for stories
    paginator_media = Paginator(media, 10000000000000000)
    page_number_media = request.GET.get('page')
    page_obj_media = paginator_media.get_page(page_number_media)

    return render(request, 'vission-mission.html',
                  {
                      'data': serializer_class.data,
        'media' : page_obj_media
                  }
                  )
        


def partener_network(request):
    """Renders the create history page."""
    assert isinstance(request, HttpRequest)
    queryset = PartenerNetwork.objects.all()
    serializer_class = PartenerNetworkSerializer(queryset, many=True)
    logo_show = PartenerLogo.objects.all()
    media = MediaDetail.objects.all()

    # Show many contacts per page for stories
    paginator_media = Paginator(media, 10000000000000000)
    page_number_media = request.GET.get('page')
    page_obj_media = paginator_media.get_page(page_number_media)

    return render(request, 'parteners-networks.html',
                  {
                      'data': serializer_class.data,
                      'logo': logo_show,
        'media' : page_obj_media
                  }
                  )
def internal_system(request):
    """Renders the create history page."""
    assert isinstance(request, HttpRequest)
    queryset = InternalSystem.objects.all()
    serializer_class = InternalSystemSerializer(queryset, many=True)
    internal_list = InternalSystemList.objects.all()
    media = MediaDetail.objects.all()

    # Show many contacts per page for stories
    paginator_media = Paginator(media, 10000000000000000)
    page_number_media = request.GET.get('page')
    page_obj_media = paginator_media.get_page(page_number_media)

    return render(request, 'internal-system.html',
                  {
                      'data': serializer_class.data,
                      'list': internal_list,
        'media' : page_obj_media
                  }
                  )

def where_we_work(request):
    """Renders the create history page."""
    assert isinstance(request, HttpRequest)
    queryset = WhereWeWork.objects.all()
    serializer_class = WhereWeWorkSerializer(queryset, many=True)
    media = MediaDetail.objects.all()

    # Show many contacts per page for stories
    paginator_media = Paginator(media, 10000000000000000)
    page_number_media = request.GET.get('page')
    page_obj_media = paginator_media.get_page(page_number_media)
    image_background = WhereWeWorkBackground.objects.all()

    return render(request, 'where-we-work.html',
                  {
                      'data': serializer_class.data,
        'media' : page_obj_media,
        'image_background' : image_background
                  }
                  )
def grass_root(request):
    """Renders the create grass_root page."""
    assert isinstance(request, HttpRequest)

about/templates/assesment_analysis.html
{% extends 'base.html' %}
{% block body %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<div class="page-title-section section">
    <div class="page-title">

    </div>
    <div class="page-breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="{% url 'home:index' %}">{% trans "Home" %}</a></li>
                <li><a href="{% url 'about:about' %}">{% trans "About Ashor" %}</a></li>
                <li><a href="{% url 'about:resources' %}">{% trans "Resources & Publications" %}</a></li>
               
                <li class="current">{% trans "Assessments & Analysis" %}</li>

            </ul>
        </div>
    </div>
</div>
<!-- Page Title Section End -->
{% for item in data %}

<!-- Blog Section Start -->
<div class="section  fix">
    <div class="container">
        <div class="row max-mb-n80">

            <div class=" col-lg-12 col-12 max-mb-50">
                <!-- Blog Wrapper Start -->
                <div class="row row-cols-1 g-0">

                    <!-- Blog Start -->
                    <div class=" col" data-aos="fade-up">


                        <!-- Page Banner Section Start -->
                        <div class="page-banner-section section overlay section-padding"
                            data-bg-image="{{ item.image_banner_assesments}}">
                            <div class="container">
                                <div class="row">
                                    <div class="col-12">
                                        <div class="page-banner-title ashor-banner-title" style="padding
                                            :50px">
                                            <h1 class="title" st>
                                            </h1>
                                        </div>


                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Page Banner Section End -->



                    </div>
                </div>
            </div>
            <!-- Blog End -->


        </div>
        <!-- Blog Wrapper End -->
    </div>


</div>



<!-- About Event Section Start -->
<div class="about-section section section-padding-top-1" style="padding-top: 50px;">
    <div class="container">


        <div class="row max-mb-n80">

            <div class=" col-lg-12 col-12 max-mb-50">
                <div class="event-content">



                    <p> {% if LANGUAGE_CODE == 'en' %}{{item.text_assesments}}
                        {% elif LANGUAGE_CODE == 'ar' %}{{item.text_assesments_ar}}
                        {% elif LANGUAGE_CODE == 'de' %}{{item.text_assesments_dr}}{% endif %}
                    </p>
                  
                </div>
                <div class="about-section section">
                    <div class="container">


                    </div>
                </div>


            </div>

        </div>
    </div>
</div>
{% endfor %}

<div class="about-section section" style="padding: 50px;">
    <div class="container">


        <div class="row">
            <div class="col-12">
                <div class="event-content">





                </div>
            </div>
        </div>
    </div>
</div>
<div class="section section-padding-bottom" style="padding-top: 50px;">
    <div class="container">

        <!--  media Bar Start -->
        <div class="row justify-content-between align-items-center max-mb-20">
            <div class="col-sm-auto col-12 max-mb-10">
                <p class="result-count">{% trans "Latest Media" %}</p>
            </div>

        </div>
        <!-- media Top Bar End -->

        <!-- media  Start -->
        <div class="row row-cols-xl-4 row-cols-lg-2 row-cols-md-2 row-cols-1 max-mb-n30">
            {% for item in media  %}
            {% if forloop.counter < 5 %} 
            <div class="col max-mb-30">
                <div class="media-6">
                    <div class="thumbnail">
                        <a class="image" href="{% url 'media:media_detail' item.id %}">
                            <img src="{{item.media_image.url}}" height="350px" style="object-fit: cover;" alt="">
                            <div class="media-overlay-bg"></div>
                        </a>
                    </div>
                    <div class="info">
                        <div class="media-caption-main">
                            <a class="category" style="color: white;"> {% if LANGUAGE_CODE == 'en' %}{{ item.category.en_name }}
                                {% elif LANGUAGE_CODE == 'ar' %} {{ item.category.ar_name }}
                                {% elif LANGUAGE_CODE == 'de' %} {{ item.category.dr_name }}{% endif %}</a>
                            <ul class="meta">
                                <li><i class="far fa-map-marker-alt"></i> {% if LANGUAGE_CODE == 'en' %}{{ item.media_location }}
                                    {% elif LANGUAGE_CODE == 'ar' %} {{ item.media_location_ar }}
                                    {% elif LANGUAGE_CODE == 'de' %} {{ item.media_location_dr }}{% endif %}</li>
                                <li><i class="far fa-calendar"></i>{{item.date|date:'d M o'}}</li>
                            </ul>
                            <h3 class="title"><a href="{% url 'media:media_detail' item.id %}"> {% if LANGUAGE_CODE == 'en' %}{{ item.media_name }}
                                {% elif LANGUAGE_CODE == 'ar' %} {{ item.media_name_ar }}
                                {% elif LANGUAGE_CODE == 'de' %} {{ item.media_name_dr }}{% endif %}</a></h3>
                        </div>
                        <div class="media-caption-collapse">
                           
                            <div class="desc">
                                <p> {% if LANGUAGE_CODE == 'en' %}{{ item.media_desc1 }}
                                    {% elif LANGUAGE_CODE == 'ar' %} {{ item.media_desc1_ar }}
                                    {% elif LANGUAGE_CODE == 'de' %} {{ item.media_desc1_dr }}{% endif %}…</p>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
         
            {% endif %} {% endfor %}


        </div>
        <!-- media  End -->


        <div class="row max-mt-50">
            <div class="col text-center">
                <a href="{% url 'media:media' %}" class="btn btn-outline-primary load-more-btn">{% trans "Read More" %} <i
                        class="far fa-long-arrow-right ms-3"></i></a>
            </div>
        </div>

    </div>
</div>
<!-- media Section End -->
{% endblock body %}

about/templates/core.html
{% extends 'base.html' %}
{% block body %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
        <div class="page-title-section section">
            <div class="page-title">
           
            </div>
            <div class="page-breadcrumb">
                <div class="container">
                    <ul class="breadcrumb">    <li><a href="{% url 'home:index' %}">{% trans "Home" %}</a></li>
                        <li><a href="{% url 'about:about' %}">{% trans "About Ashor" %}</a></li>
                        <li class="current">{% trans "Core" %}</li>
        
                    </ul>
                </div>
            </div>
        </div>
        <!-- Page Title Section End -->
        <!-- Blog Section Start -->
        <div class="section  fix">
            <div class="container">
                <div class="row max-mb-n50">

                    <div class="col-lg-12 col-12 order-lg-1 max-mb-50">
                        <!-- Blog Wrapper Start -->
                        <div class="row row-cols-1 g-0">

                            <!-- Blog Start -->
                            <div class=" col" data-aos="fade-up">

{% for item in core_bg %}
                                <!-- Page Banner Section Start -->
                                <div class="page-banner-section section overlay section-padding"
                                    data-bg-image="{{ item.image_bg_core.url}}">
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="page-banner-title ashor-banner-title">
                                                    <h1 class="title" style="padding: 50px;">
                                                    </h1>
                                                </div>


                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Page Banner Section End -->
{% endfor %}


                            </div>
                        </div>
                    </div>
                    <!-- Blog End -->


                </div>
                <!-- Blog Wrapper End -->
            </div>


        </div>
        
        <div class="section  fix">
            <div class="container">
                <div class="row max-mb-n80">

                    <div class=" col-lg-12 col-12 max-mb-50">
                        <!-- Blog Wrapper Start -->
                        <div class="row row-cols-1 g-0">
                         
                          
                            {% for item in core_bg %}
                            <p style="padding-top: 50px;">{% if LANGUAGE_CODE == 'en' %}{{item.textcore_desc1}}
                                {% elif LANGUAGE_CODE == 'ar' %}{{item.textcore_desc1_ar}}
                                {% elif LANGUAGE_CODE == 'de' %}{{item.textcore_desc1_dr}}{% endif %}.</p>{% endfor %}
                                <div class="team-section section " style="padding-top: 50px;">
                                    <div class="container">
                                     
                                    
                                        <div class="row ht-team-member-style-three max-mb-n50">
                                            {% for item in core %}
                                            <div class="col-lg-3 col-md-6 col-sm-6 max-mb-50">
                                                <div class="grid-item ">
                                                    <div class="ht-team-member">
                                                        <div class="team-image">
                                                            <img class="img-fluid" src="{{ item.core_image.url}}" alt="" height="350px" style="object-fit: cover; height: 250px;">
                                                            <div class="social-networks">
                                                                <div class="inner">
                                                                    <a target="_blank" href="{% url 'about:core_detail' item.id %}"  >Read more
                                                                    </a>
                                                                    
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="team-info text-center">
                                                            <h3 class="name">{% if LANGUAGE_CODE == 'en' %}{{item.core_name}}
                                                                {% elif LANGUAGE_CODE == 'ar' %}{{item.core_name_ar}}
                                                                {% elif LANGUAGE_CODE == 'de' %}{{item.core_name_dr}}{% endif %} 
                                                                <br></h3>
                                                            <div class="position">{% if LANGUAGE_CODE == 'en' %}{{item.core_position}}
                                                                {% elif LANGUAGE_CODE == 'ar' %}{{item.core_position_ar}}
                                                                {% elif LANGUAGE_CODE == 'de' %}{{item.core_position_dr}}{% endif %}
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                              
                                            {% endfor %}

                                   
                                
                                        </div>
                                    </div>
                                </div>
                             
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <div class="section  fix">
          
            <div class="about-section section" style="padding: 50px;">
                <div class="container">
        
        
                    <div class="row">
                        <div class="col-12">
                            <div class="event-content">
        
        
        
        
        
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="section section-padding-bottom" style="padding-top: 50px;">
                <div class="container">
        
                    <!--  media Bar Start -->
                    <div class="row justify-content-between align-items-center max-mb-20">
                        <div class="col-sm-auto col-12 max-mb-10">
                            <p class="result-count">{% trans "Latest Media" %}</p>
                        </div>
        
                    </div>
                    <!-- media Top Bar End -->
        
                    <!-- media  Start -->
                    <div class="row row-cols-xl-4 row-cols-lg-2 row-cols-md-2 row-cols-1 max-mb-n30">
                        {% for item in media  %}
                        {% if forloop.counter < 5 %} 
                        <div class="col max-mb-30">
                            <div class="media-6">
                                <div class="thumbnail">
                                    <a class="image" href="{% url 'media:media_detail' item.id %}">
                                        <img src="{{item.media_image.url}}" height="350px" style="object-fit: cover;" alt="">
                                        <div class="media-overlay-bg"></div>
                                    </a>
                                </div>
                                <div class="info">
                                    <div class="media-caption-main">
                                        <a class="category" style="color: white;"> {% if LANGUAGE_CODE == 'en' %}{{ item.category.en_name }}
                                            {% elif LANGUAGE_CODE == 'ar' %} {{ item.category.ar_name }}
                                            {% elif LANGUAGE_CODE == 'de' %} {{ item.category.dr_name }}{% endif %}</a>
                                        <ul class="meta">
                                            <li><i class="far fa-map-marker-alt"></i> {% if LANGUAGE_CODE == 'en' %}{{ item.media_location }}
                                                {% elif LANGUAGE_CODE == 'ar' %} {{ item.media_location_ar }}
                                                {% elif LANGUAGE_CODE == 'de' %} {{ item.media_location_dr }}{% endif %}</li>
                                            <li><i class="far fa-calendar"></i>{{item.date|date:'d M o'}}</li>
                                        </ul>
                                        <h3 class="title"><a href="{% url 'media:media_detail' item.id %}"> {% if LANGUAGE_CODE == 'en' %}{{ item.media_name }}
                                            {% elif LANGUAGE_CODE == 'ar' %} {{ item.media_name_ar }}
                                            {% elif LANGUAGE_CODE == 'de' %} {{ item.media_name_dr }}{% endif %}</a></h3>
                                    </div>
                                    <div class="media-caption-collapse">
                                       
                                        <div class="desc">
                                            <p> {% if LANGUAGE_CODE == 'en' %}{{ item.media_desc1 }}
                                                {% elif LANGUAGE_CODE == 'ar' %} {{ item.media_desc1_ar }}
                                                {% elif LANGUAGE_CODE == 'de' %} {{ item.media_desc1_dr }}{% endif %}…</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
        
                        </div>
                     
                        {% endif %} {% endfor %}
        
        
                    </div>
                    <!-- media  End -->
        
        
                    <div class="row max-mt-50">
                        <div class="col text-center">
                            <a href="{% url 'media:media' %}" class="btn btn-outline-primary load-more-btn">{% trans "Read More" %} <i
                                    class="far fa-long-arrow-right ms-3"></i></a>
                        </div>
                    </div>
        
                </div>
            </div>
      
            {% endblock body %} 