aifrd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _



urlpatterns = [
    # django rest api
   
    path('api-auth/', include('rest_framework.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('what_we_are_doing/', include('what_we_are_doing.urls', namespace='what_we_are_doing')),
    path('about/', include('about.urls', namespace='about')),
    path('get_involved/', include('get_involved.urls', namespace='get_involved')),
    path('media/', include('mediapage.urls', namespace='media')),


)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_url = None
admin.site.site_header = 'HuminImp Administration'

home/urls.py
from django.urls import include, path

from . import views
from . import api


app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
 
    path('contact', views.contact, name='contact'),

]

mediapage/urls.py
from django.urls import path
from . import views

app_name = 'media'

urlpatterns = [
    path('', views.media_list, name='media'),
  path("media_filter/", views.media_filter, name="media_filter"),

    path("media/<int:id>/", views.media_detail, name="media_detail"),

]

mediapage/models.py
from django.db import models
from .validators import validate_image_extension
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinValueValidator

from datetime import date



class MediaBackgroundImage(models.Model):
    bg_image_story = models.FileField(
        validators=[validate_image_extension], upload_to='background/story/',default='', blank=True)



class Category(models.Model):
    ar_name = models.CharField(blank=False, null=False, max_length=100)
    en_name = models.CharField(blank=False, null=False, max_length=100)
    dr_name = models.CharField(blank=False, null=False, max_length=100)

    def __str__(self):
        return self.en_name


class MediaDetail(models.Model):

    media_image = models.FileField(
        validators=[validate_image_extension], default='',upload_to='background/media/', blank=True)
   
    date = models.DateField(default=date.today, blank=True)
    media_location = models.CharField(
        max_length=300, default='', blank=True)
    media_location_ar = models.CharField(
        max_length=300, default='', blank=True)
    media_location_dr = models.CharField(
        max_length=300, default='', blank=True)
    media_name = models.CharField(
        max_length=300, default='', blank=True)
    media_name_ar = models.CharField(
        max_length=300, default='', blank=True)
    media_name_dr = models.CharField(
        max_length=300, default='', blank=True)
    category = models.ForeignKey(
        'Category',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    media_desc1 = models.TextField(
        max_length=1000, default='', blank=True)
    media_desc1_ar = models.TextField(
        max_length=1000, default='', blank=True)
    media_desc1_dr = models.TextField(
        max_length=1000, default='', blank=True)

    media_desc2 = models.TextField(
        max_length=1000, default='', blank=True)
    media_desc2_ar = models.TextField(
        max_length=1000, default='', blank=True)
    media_desc2_dr = models.TextField(
        max_length=1000, default='', blank=True)

    media_desc3 = models.TextField(
        max_length=1000, default='', blank=True)
    media_desc3_ar = models.TextField(
        max_length=1000, default='', blank=True)
    media_desc3_dr = models.TextField(
        max_length=1000, default='', blank=True)
    views = models.PositiveIntegerField(default=0, validators=[
            MinValueValidator(0)
    ])

    class Meta:
        ordering = ['-date']

mediapage/views.py
from django.shortcuts import render
from django.db.models import F

from .models import MediaDetail, MediaBackgroundImage
from .serializers import MediaDetailSerializer, MediaBackgroundImageSerializer
from django.http import HttpRequest
from .filters import MediaDetailFilter
# from .form import StoryDetailForm
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render

def media_filter(request):

    order = request.GET.get("order", None)
    if order == "popularity":
        media = MediaDetail.objects.order_by("-views")
    elif order == "latest":
        media = MediaDetail.objects.all().order_by("-date")
    else:
        media = MediaDetail.objects.all()
        
    media = MediaDetailFilter(request.GET, queryset=media).qs
  
    

    if media:
        context = {
            "media": media,
        }  # template name

    else:
        context = {"message": "There are no media available at the moment."}
    return render(request, "media_filter.html", context)

def media_list(request):

    media = MediaDetail.objects.all().order_by("-date")
    myfilter = MediaDetailFilter(request.GET, queryset=media)
    media = myfilter.qs
    media_bg = MediaBackgroundImage.objects.all()

    # Show many contacts per page.
    paginator = Paginator(media, 100000000000000000000)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    print(page_obj)
    print("hello")

    if media:
        context = {
            "media": page_obj,
            "myfilter": myfilter,
            'media_bg':media_bg
        }  # template name

    else:
        context = {"message": "There are no media available at the moment."}
    return render(request, "media.html", context)


def media_detail(request, id):
    media = get_object_or_404(MediaDetail, pk=id)

    media = MediaDetail.objects.filter(id=id).last()
    media.views = F("views") + 1
    media.save()
    media.refresh_from_db()
    medias = MediaDetail.objects.all()

    # Show many contacts per page for stories
    paginator_media = Paginator(medias, 10000000000000000)
    page_number_media = request.GET.get('page')
    page_obj_media = paginator_media.get_page(page_number_media)

    context = {"media": media,  'num_visits': media.views, 'medias': page_obj_media}
    return render(request, "media-details.html", context)



def clear(request):
    return HttpResponse("")

mediapage/templates/media-details.html
{% extends 'base.html' %}
{% block body %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
        <div class="page-title-section section">
            <div class="page-title">

            </div>
            <div class="page-breadcrumb">
                <div class="container">
                    <ul class="breadcrumb">
                        <li><a href="{% url 'home:index' %}">{% trans "Home" %}</a></li>
        
                        <li class="current">{% trans "Media" %}</li>

                    </ul>
                </div>
            </div>
        </div>
        <!-- Page Title Section End -->


        <!-- About Event Section Start -->
        <div class="about-event-section section">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <!-- Section Title Start -->
                        <div class="section-title text-center" data-aos="fade-up">

                            <h2 class="title fz-12 heading-color">{% if LANGUAGE_CODE == 'en' %}{{ media.media_name }}
                                {% elif LANGUAGE_CODE == 'ar' %} {{ media.media_name }}{% endif %}</h2>
                            <div class="event-entry-meta">
                                <div class="meta-item">
                                    <i class="meta-icon fal fa-map-marker-alt"></i>
                                    <span> {% if LANGUAGE_CODE == 'en' %}{{ media.media_location }}
                                        {% elif LANGUAGE_CODE == 'ar' %} {{ media.media_location_ar }}{% endif %}</span>
                                </div>

                                <div class="meta-item">
                                    <i class="meta-icon fal fa-calendar"></i>
                                    <span>{{ media.date }}</span>
                                </div>


                            </div>





                        </div>

                    </div>
                    <div class=" col" data-aos="fade-up">


                        <!-- Page Banner Section Start -->
                        <div class="page-banner-section section overlay section-padding"
                            data-bg-image="{{ media.media_image.url }}">
                            <div class="container">
                                <div class="row">
                                    <div class="col-12">
                                        <div class="page-banner-title ashor-banner-title">
                                            <h1 class="title" style="padding: 50px;">
                                            </h1>
                                        </div>


                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Page Banner Section End -->



                    </div>
                </div>

            </div>
        </div>
        <!-- About Event Section End -->


        <!-- Blog Section Start -->
        <div class="section  fix">
            <div class="container">
                <div class="row ">

                    <div class="col-lg-12 col-12 ">
                        <!-- Blog Wrapper Start -->
                        <div class="row row-cols-1 ">

                            <!-- Blog Start -->
                            <div class="blog-3 blog-details col" data-aos="fade-up">


                                <div class="info">
                                    <div class="desc">
                                        <p>{% if LANGUAGE_CODE == 'en' %}{{ media.media_desc1 }}
                                            {% elif LANGUAGE_CODE == 'ar' %} {{ media.media_desc1_ar }}
                                            {% elif LANGUAGE_CODE == 'de' %} {{ media.media_desc1_dr }}{% endif %}</p>

           
                                       
                                            <p>{% if LANGUAGE_CODE == 'en' %}{{ media.media_desc2 }}
                                                {% elif LANGUAGE_CODE == 'ar' %} {{ media.media_desc2_ar }}
                                                {% elif LANGUAGE_CODE == 'de' %} {{ media.media_desc2_dr }}{% endif %}</p>
                             

                                        <p>{% if LANGUAGE_CODE == 'en' %}{{ media.media_desc3 }}
                                            
                                            {% elif LANGUAGE_CODE == 'ar' %} {{ media.media_desc3_ar }}
                                            {% elif LANGUAGE_CODE == 'de' %} {{ media.media_desc3_dr }}{% endif %}</p>

                                    </div>

                                    <div class="row justify-content-between align-items-center max-mt-50">
                                        <div class="col-auto">
                                            <div class="entry-post-tags">
                                                <div class="tag-label">
                                                    <span class="tag-icon far fa-tags"></span>
                                                </div>
                                                <div class="tag">
                                                    <a href="#"> {% if LANGUAGE_CODE == 'en' %}{{ media.category.en_name }}
                                                        {% elif LANGUAGE_CODE == 'ar' %} {{ media.category.ar_name }}
                                                        {% elif LANGUAGE_CODE == 'de' %} {{ media.category.dr_name }}{% endif %} </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-auto">
                                            <div class="post-share">
                                                <span class="label">Share this post</span>
                                                <div class="media">
                                                    <span class="icon"><i class="fas fa-share-alt"></i></span>
                                                    <div class="list">
                                                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                                                        <a href="#"><i class="fab fa-twitter"></i></a>
                                                        <a href="#"><i class="fab fa-linkedin"></i></a>
                                                        <a href="#"><i class="fab fa-tumblr-square"></i></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Blog End -->


                    </div>
                    <!-- Blog Wrapper End -->
                </div>



            </div>
        </div>
    </div>
    <div class="section section-padding-bottom" style="padding-top: 50px;">
        <div class="container">

            <!--  media Bar Start -->
            <div class="row justify-content-between align-items-center max-mb-20">
                <div class="col-sm-auto col-12 max-mb-10">
                    <p class="result-count">{% trans "Latest Media" %}</p>
                </div>

            </div>
            <!-- media Top Bar End -->

            <!-- media  Start -->
            <div class="row row-cols-xl-4 row-cols-lg-2 row-cols-md-2 row-cols-1 max-mb-n30">
                {% for media in medias  %}
                {% if forloop.counter < 5 %} 
                <div class="col max-mb-30">
                    <div class="media-6">
                        <div class="thumbnail">
                            <a class="image" href="{% url 'media:media_detail' media.id %}">
                                <img src="{{media.media_image.url}}" height="350px" style="object-fit: cover;" alt="">
                                <div class="media-overlay-bg"></div>
                            </a>
                        </div>
                        <div class="info">
                            <div class="media-caption-main">
                                <a class="category" style="color: white;"> {% if LANGUAGE_CODE == 'en' %}{{ media.category.en_name }}
                                    {% elif LANGUAGE_CODE == 'ar' %} {{ media.category.ar_name }}
                                    {% elif LANGUAGE_CODE == 'de' %} {{ media.category.dr_name }}{% endif %}</a>
                                <ul class="meta">
                                    <li><i class="far fa-map-marker-alt"></i> {% if LANGUAGE_CODE == 'en' %}{{ media.media_location }}
                                        {% elif LANGUAGE_CODE == 'ar' %} {{ media.media_location_ar }}
                                        {% elif LANGUAGE_CODE == 'de' %} {{ media.media_location_dr }}{% endif %}</li>
                                    <li><i class="far fa-calendar"></i>{{media.date|date:'d M o'}}</li>
                                </ul>
                                <h3 class="title"><a href="{% url 'media:media_detail' media.id %}"> {% if LANGUAGE_CODE == 'en' %}{{ media.media_name }}
                                    {% elif LANGUAGE_CODE == 'ar' %} {{ media.media_name_ar }}
                                    {% elif LANGUAGE_CODE == 'de' %} {{ media.media_name_dr }}{% endif %}</a></h3>
                            </div>
                            <div class="media-caption-collapse">
                               
                                <div class="desc">
                                    <p> {% if LANGUAGE_CODE == 'en' %}{{ media.media_desc1 }}
                                        {% elif LANGUAGE_CODE == 'ar' %} {{ media.media_desc1_ar }}
                                        {% elif LANGUAGE_CODE == 'de' %} {{ media.media_desc1_dr }}{% endif %}…</p>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
             
                {% endif %} {% endfor %}                
        

            </div>
            <!-- media  End -->


            <div class="row max-mt-50">
                <div class="col text-center">
                    <a href="{% url 'media:media' %}" class="btn btn-outline-primary load-more-btn">{% trans "Read More" %} <i
                            class="far fa-long-arrow-right ms-3"></i></a>
                </div>
            </div>

        </div>
    </div>
    {% endblock body %}

mediapage/templates/media.html
{% extends 'base.html' %}
{% block body %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
        <!-- Page Title Section Start -->
        <div class="page-title-section section">
            <div class="page-title">
           
            </div>
            <div class="page-breadcrumb">
                <div class="container">
                    <ul class="breadcrumb">    
                        <li><a href="{% url 'home:index' %}">{% trans "Home" %}</a></li>
                        <li class="current">{% trans "Media" %}</li>
        
                    </ul>
                </div>
            </div>
        </div>        <!-- Page Title Section End -->
        <!-- Blog Section Start -->
        <div class="section  fix">
            <div class="container">
                <div class="row max-mb-n50">

                    <div class="col-lg-12 col-12 order-lg-1 max-mb-50">
                        <!-- Blog Wrapper Start -->
                        <div class="row row-cols-1 g-0">

                            <!-- Blog Start -->
                            <div class=" col" data-aos="fade-up">

                                {% for item in media_bg %}

                                <!-- Page Banner Section Start -->
                                <div class="page-banner-section section overlay section-padding"
                                    data-bg-image="{{ item.bg_image_story.url}}">
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="page-banner-title ashor-banner-title">
                                                    <h1 class="title" style="padding: 50px;">
                                                    </h1>
                                                </div>


                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}

                                <!-- Page Banner Section End -->



                            </div>
                        </div>
                    </div>
                    <!-- Blog End -->


                </div>
                <!-- Blog Wrapper End -->
            </div>


        </div>
    </div>

    <!-- Blog Section End -->


    <!-- media Section Start -->
    <div class="section section-padding-bottom" style="padding-top: 50px;">
        <div class="container">

            <!-- media Top Bar Start -->
            <div class="row justify-content-between align-items-center max-mb-20">
                <div class="col-sm-auto col-12 max-mb-10">
                  <p class="result-count">{% trans "We found" %} <span>{{media|length}}</span> {% trans "blogs available for you" %}</p>
                </div>
                
                <div class="col-sm-auto col-12 max-mb-10">
                  <div class="col-sm-auto col-12 max-mb-10">
                    <div class="col-sm-auto col-12 max-mb-10">
                        {% if LANGUAGE_CODE == 'en' %}
                    <select class="sort-by" onchange="location = this.value;">
                      {% elif LANGUAGE_CODE == 'ar' %} 
                      <select class="sort-by-arabic" onchange="location = this.value;">
                        {% endif %}  
                                 <option value="{% url 'media:media_filter' %}">{% trans "Default" %}</option>
                        <option value="{% url 'media:media_filter' %}?order=popularity">{% trans "Popularity" %}</option>
                        <option  value="{% url 'media:media_filter' %}?order=latest">{% trans "Latest" %}</option>
                        <optgroup label="__">
                          {% for category in categories  %}
                        <option value="{% url 'media:media_filter' %}?category={{category}}">
                          {% if LANGUAGE_CODE == 'en' %}
                            {{ category.en_name }}
                          {% elif LANGUAGE_CODE == 'ar' %} 
                            {{ category.ar_name }}
                            {% elif LANGUAGE_CODE == 'de' %} 
                            {{ category.dr_name }}
                          {% endif %}
                        </option></a>
                        {% endfor %}
                      </optgroup>
            
                        
                      </select>
                    </div>
                   
                    
                  </div>
          
                  
                </div>
              </div>
            <div class="section section-fluid section-padding">
                <div class="container">
                   
                    <div class="row row-cols-xl-4 row-cols-lg-2 row-cols-md-2 row-cols-1 max-mb-n30">
                        {% for item in media  %}

                        <div class="col max-mb-30">
                            <div class="media-6">
                                <div class="thumbnail">
                                    <a class="image" href="{% url 'media:media_detail' id=item.id %}">
                                        <img src="{{item.media_image.url}}" alt="" height="350px" style="object-fit: cover;" >
                                        <div class="media-overlay-bg"></div>
                                    </a>
                                </div>
                                <div class="info">
                                    <div class="media-caption-main">
                                        <a class="category" style="color: white;"> {% if LANGUAGE_CODE == 'en' %}{{ item.category.en_name }}
                                            {% elif LANGUAGE_CODE == 'ar' %} {{ item.category.ar_name }}
                                            {% elif LANGUAGE_CODE == 'de' %} {{ item.category.dr_name }}{% endif %}</a>
                                        <ul class="meta">
                                            <li><i class="far fa-map-marker-alt"></i> {% if LANGUAGE_CODE == 'en' %}{{ item.media_location }}
                                                {% elif LANGUAGE_CODE == 'ar' %} {{ item.media_location_ar }}
                                                {% elif LANGUAGE_CODE == 'de' %} {{ item.media_location_dr }}{% endif %}</li>
                                            <li><i class="far fa-calendar"></i>{{ item.date }}</li>
                                        </ul>
                                        <h3 class="title"><a href="{% url 'media:media_detail' item.id %}"> {% if LANGUAGE_CODE == 'en' %}{{ item.media_name }}
                                            {% elif LANGUAGE_CODE == 'ar' %} {{ item.media_name_ar }}
                                            {% elif LANGUAGE_CODE == 'de' %} {{ item.media_name_dr }}{% endif %}</a></h3>
                                    </div>
                                    <div class="media-caption-collapse">
                                       
                                        <div class="desc">
                                            <p style="  display: -webkit-box;
                                            -webkit-line-clamp: 3;
                                            -webkit-box-orient: vertical;
                                            overflow: hidden;"> {% if LANGUAGE_CODE == 'en' %}{{ item.media_desc1 }}
                                                {% elif LANGUAGE_CODE == 'ar' %} {{ item.media_desc1_ar }}
                                                {% elif LANGUAGE_CODE == 'de' %} {{ item.media_desc1_dr }}{% endif %}…</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor  %}

    
                    </div>
    
                </div>
            </div>
      
        

        </div>
    </div>
    <!-- media Section End -->

    <!-- About Event Section End -->
    {% endblock body %}