aifrd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _



urlpatterns = [
    # django rest api
   
    path('api-auth/', include('rest_framework.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('what_we_are_doing/', include('what_we_are_doing.urls', namespace='what_we_are_doing')),
    path('about/', include('about.urls', namespace='about')),
    path('get_involved/', include('get_involved.urls', namespace='get_involved')),
    path('media/', include('mediapage.urls', namespace='media')),


)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_url = None
admin.site.site_header = 'HuminImp Administration'

home/urls.py
from django.urls import include, path

from . import views
from . import api


app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
 
    path('contact', views.contact, name='contact'),

]

mediapage/urls.py
from django.urls import path
from . import views

app_name = 'media'

urlpatterns = [
    path('', views.media_list, name='media'),
  path("media_filter/", views.media_filter, name="media_filter"),

    path("media/<int:id>/", views.media_detail, name="media_detail"),

]

what_we_are_doing/urls.py
from django.urls import path
from . import views

app_name = 'what_we_are_doing'

urlpatterns = [
    path('', views.what_we_are_doing, name='what_we_are_doing'),
   
    path('themes/', views.themes, name='themes'),
    # path('themes_details/<int:id>', views.themes_details, name='themes_details'),
    # path('themes/<int:id>/', views.theme_detail, name='themes_details'),
    path('themes/<int:theme_id>/', views.theme_detail, name='themes_details'),
    path('project/', views.project, name='project'),

]

what_we_are_doing/models.py
from django.db import models
from .validators import validate_file_extension, validate_image_extension
from datetime import date

# Create your models here.
class WhatWeAreDoing(models.Model):
    image_bg_whatWeAreDoing = models.FileField(
        validators=[validate_image_extension], upload_to='background/WhatWeAreDoing/', blank=True, )

    text_WhatWeAreDoing = models.TextField(
        max_length=1000, default='', blank=True, )
    text_WhatWeAreDoing_ar = models.TextField(
        max_length=1000, default='', blank=True, )
    text_WhatWeAreDoing_dr = models.TextField(
        max_length=1000, default='', blank=True, )

    text_project = models.TextField(
        max_length=1000, default='',  blank=True,)
    text_project_ar = models.TextField(
        max_length=1000, default='',  blank=True,)
    text_project_dr = models.TextField(
        max_length=1000, default='',  blank=True,)
    image_bg_whatWeAreDoing_project = models.FileField(
        validators=[validate_image_extension], upload_to='background/about/', blank=True, )
    text_themes = models.TextField(
        max_length=1000, default='',  blank=True,)
    text_themes_ar = models.TextField(
        max_length=1000, default='',  blank=True,)
    text_themes_dr = models.TextField(
        max_length=1000, default='',  blank=True,)

class ThemeBackgroundImage(models.Model):
    image_bg_theme = models.FileField(
        validators=[validate_image_extension], upload_to='background/WhatWeAreDoing/', blank=True, )


class Themes(models.Model):
    id = models.AutoField(primary_key=True)

    themes_icons = models.FileField(
        validators=[validate_image_extension], upload_to='background/themes/', blank=True, )
    themes_details_image = models.FileField(
        validators=[validate_image_extension], upload_to='background/themes/', blank=True, ) 
    themes_title = models.CharField(
        max_length=1000, default='', blank=True, )
    themes_title_ar = models.CharField(
        max_length=1000, default='', blank=True, )
    themes_title_dr = models.CharField(
        max_length=1000, default='', blank=True, )
    themes_dsc1 = models.TextField(
        max_length=1000, default='', blank=True, )
    themes_dsc1_ar = models.TextField(
        max_length=1000, default='', blank=True, )
    themes_dsc1_dr = models.TextField(
        max_length=1000, default='', blank=True, )

    themes_dsc2 = models.TextField(
        max_length=1000, default='', blank=True, )
    themes_dsc2_ar = models.TextField(
        max_length=1000, default='', blank=True, )
    themes_dsc2_dr = models.TextField(
        max_length=1000, default='', blank=True, )

class Category(models.Model):
    ar_name = models.CharField(blank=False, null=False, max_length=100)
    en_name = models.CharField(blank=False, null=False, max_length=100)
    dr_name = models.CharField(blank=False, null=False, max_length=100)

    def __str__(self):
        return self.en_name
YEAR = (
    ('2018', "2018"),
    ('2019', "2019"),
        ('2020', "2020"),
        ('2021', "2021"),
        ('2022', "2022"),
        ('2023', "2023"),

)

class Project(models.Model):
 
    project_image = models.FileField(
        validators=[validate_image_extension], upload_to='background/themes/', blank=True, ) 
    project_name = models.CharField(
        max_length=1000, default='', blank=True, )
    project_name_ar = models.CharField(
        max_length=1000, default='', blank=True, )
    project_name_dr = models.CharField(
        max_length=1000, default='', blank=True, )
    project_date = models.CharField(
        max_length=1000, default='', blank=True, )
    year = models.CharField(choices=YEAR, max_length=6)

    category =  models.ForeignKey(
        'Category',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    project_location = models.CharField(
        max_length=300, default='', blank=True)
    project_location_ar = models.CharField(
        max_length=300, default='', blank=True)
    project_location_dr = models.CharField(
        max_length=300, default='', blank=True)
    project_parteners = models.CharField(
        max_length=1000, default='', blank=True, )
    project_parteners_ar = models.CharField(
        max_length=1000, default='', blank=True, )
    project_parteners_dr = models.CharField(
        max_length=1000, default='', blank=True, )
    project_dsc1 = models.TextField(
        max_length=1000, default='', blank=True, )
    project_dsc1_ar = models.TextField(
        max_length=1000, default='', blank=True, )
    project_dsc1_dr = models.TextField(
        max_length=1000, default='', blank=True, )

what_we_are_doing/views.py
from email.message import EmailMessage
from django.shortcuts import redirect, render
from django.http import HttpResponse
from rest_framework import generics, permissions
from .serializers import WhatWeAreDoingSerializer, ThemesSerializer, ProjectSerializer, ThemeBackgroundImageSerializer
from django.http import HttpRequest
from rest_framework.renderers import JSONRenderer, TemplateHTMLRenderer
from django.core.paginator import Paginator
from django.utils.translation import get_language, activate
from what_we_are_doing.models import WhatWeAreDoing, Themes, Project, ThemeBackgroundImage
from django.core.mail import send_mail,  EmailMessage
from mediapage.models import MediaDetail
from django.shortcuts import get_object_or_404, render
from .filters import ThemesDetailFilter, ProjectDetailFilter


renderer_classes = (JSONRenderer, TemplateHTMLRenderer,)
template_name = "applicantsList.html"


def translate(language):
    cur_language = get_language()
    try:
        activate(language)
    finally:
        activate(cur_language)


def what_we_are_doing(request):
    """Renders the create what_we_are_doing page."""
    assert isinstance(request, HttpRequest)
    queryset = WhatWeAreDoing.objects.all()
    serializer_class = WhatWeAreDoingSerializer(queryset, many=True)
    media = MediaDetail.objects.all()

    # Show many contacts per page for stories
    paginator_media = Paginator(media, 10000000000000000)
    page_number_media = request.GET.get('page')
    page_obj_media = paginator_media.get_page(page_number_media)

    return render(request, 'what-we-are-doing.html',
                  {
                      'data': serializer_class.data,
        'media' : page_obj_media
                  }
                  )

# def themes(request):
#     """Renders the create themes page."""
#     themes = Themes.objects.all()

#     # filters
#     myfilter = ThemesDetailFilter(request.GET, queryset=themes)
     
#     context = {
#         'themes': themes,
#         'myfilter': myfilter,
#     }  # template name

#     return render(request, 'themes.html', context)


from django.shortcuts import render

def themes(request):
    """Renders the create themes page."""
    themes = Themes.objects.all()
    themes_bg = ThemeBackgroundImage.objects.all()
    # filters
    myfilter = ThemesDetailFilter(request.GET, queryset=themes)
    media = MediaDetail.objects.all()

    # Show many contacts per page for stories
    paginator_media = Paginator(media, 10000000000000000)
    page_number_media = request.GET.get('page')
    page_obj_media = paginator_media.get_page(page_number_media)

    context = {
        'themes': themes,
        'myfilter': myfilter,
        'themes_bg': themes_bg,
        'media' : page_obj_media
    }  # template name

    return render(request, 'themes.html', context)


# def themes_details(request, id):
#     """Renders the create themes page."""
 
#     themes = Themes.objects.get(id=id)

#     context = {'item': themes}
#     return render(request, 'themes-details.html', context)

def theme_detail(request, theme_id):
    theme = get_object_or_404(Themes, pk=theme_id)
    context = {'theme': theme}
    return render(request, 'themes-details.html', context)

def project(request):
    """Renders the create what_we_are_doing page."""
    assert isinstance(request, HttpRequest)
 
    order = request.GET.get("order", None)
    if order == "popularity":
        project = Project.objects.order_by("-views")
    elif order == "latest":
        project = Project.objects.all().order_by("-date")
    else:
        project = Project.objects.all()
    serializer_class = ProjectDetailFilter(request.GET, queryset=project).qs

    media = MediaDetail.objects.all()

    # Show many contacts per page for stories
    paginator_media = Paginator(media, 10000000000000000)
    page_number_media = request.GET.get('page')
    page_obj_media = paginator_media.get_page(page_number_media)

    return render(request, 'projects.html',
        {
            'data': serializer_class,
        'media' : page_obj_media
        }
        )

what_we_are_doing/templates/themes.html
{% extends 'base.html' %}
{% block body %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<div class="page-title-section section">
    <div class="page-title">

    </div>
    <div class="page-breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="{% url 'home:index' %}">{% trans "Home" %}</a></li>
                <li><a href="{% url 'what_we_are_doing:what_we_are_doing' %}">{% trans "What we are doing" %}</a></li>

                <li class="current">{% trans "Ashor themes" %} </a></li>

              

            </ul>
        </div>
    </div>
</div>
<!-- Page Title Section End -->
<!-- Blog Section Start -->
<div class="section  fix">
    <div class="container">
        <div class="row max-mb-n50">

            <div class="col-lg-12 col-12 order-lg-1 max-mb-50">
                <!-- Blog Wrapper Start -->
                <div class="row row-cols-1 g-0">

                    <!-- Blog Start -->
                    <div class=" col" data-aos="fade-up">

                        {% for item in themes_bg %}

                        <!-- Page Banner Section Start -->
                        <div class="page-banner-section section overlay section-padding"
                            data-bg-image="{{ item.image_bg_theme.url}}">
                            <div class="container">
                                <div class="row">
                                    <div class="col-12">
                                        <div class="page-banner-title ashor-banner-title">
                                            <h1 class="title" style="padding: 50px;">
                                            </h1>
                                        </div>


                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Page Banner Section End -->
{% endfor %}


                    </div>
                </div>
            </div>
            <!-- Blog End -->


        </div>
        <!-- Blog Wrapper End -->
    </div>


</div>
<!-- Feature Section Start -->
<div class="section" style="padding-top: 50px;">
    <div class="container">

        <!-- Section Title Start -->
        <div class="section-title text-center" data-aos="fade-up">

        </div>
        <!-- Section Title End -->

        <!-- themes Wrapper Start -->
        <div class="row row-cols-xl-3 row-cols-sm-2 row-cols-1 max-mb-n30">
            {% for theme in themes %}

            <!-- themes Start (Icon Box) -->
            <div class="col max-mb-30" data-aos="fade-up">
                <a href="{% url 'what_we_are_doing:themes_details' theme_id=theme.id %}" class="icon-box text-center" data-vivus-hover>
                    <div class="icon"><img class="" src="{{ theme.themes_icons}}" alt="">
                    </div>
                    <div class="content">
                        <h3 class="title"> {% if LANGUAGE_CODE == 'en' %}{{theme.themes_title}}
                            {% elif LANGUAGE_CODE == 'ar' %}{{theme.themes_title_ar}}
                            {% elif LANGUAGE_CODE == 'de' %}{{theme.themes_title_dr}}{% endif %}
                      </h3>
                        <div class="desc">

                        </div>
                        <span class="link">{% trans "THEMES" %} <i class="far fa-long-arrow-right"></i></span>
                    </div>
                </a>
            </div>
            <!-- themes Start (Icon Box) -->
            {% endfor %}

        </div>
        <!-- themes Wrapper End -->

    </div>
</div>
<div class="about-section section" style="padding: 50px;">
    <div class="container">


        <div class="row">
            <div class="col-12">
                <div class="event-content">





                </div>
            </div>
        </div>
    </div>
</div>
<div class="section section-padding-bottom" style="padding-top: 50px;">
    <div class="container">

        <!--  media Bar Start -->
        <div class="row justify-content-between align-items-center max-mb-20">
            <div class="col-sm-auto col-12 max-mb-10">
                <p class="result-count">{% trans "Latest Media" %}</p>
            </div>

        </div>
        <!-- media Top Bar End -->

        <!-- media  Start -->
        <div class="row row-cols-xl-4 row-cols-lg-2 row-cols-md-2 row-cols-1 max-mb-n30">
            {% for item in media  %}
            {% if forloop.counter < 5 %} 
            <div class="col max-mb-30">
                <div class="media-6">
                    <div class="thumbnail">
                        <a class="image" href="{% url 'media:media_detail' item.id %}">
                            <img src="{{item.media_image.url}}" height="350px" style="object-fit: cover;" alt="">
                            <div class="media-overlay-bg"></div>
                        </a>
                    </div>
                    <div class="info">
                        <div class="media-caption-main">
                            <a class="category" style="color: white;"> {% if LANGUAGE_CODE == 'en' %}{{ item.category.en_name }}
                                {% elif LANGUAGE_CODE == 'ar' %} {{ item.category.ar_name }}
                                {% elif LANGUAGE_CODE == 'de' %} {{ item.category.dr_name }}{% endif %}</a>
                            <ul class="meta">
                                <li><i class="far fa-map-marker-alt"></i> {% if LANGUAGE_CODE == 'en' %}{{ item.media_location }}
                                    {% elif LANGUAGE_CODE == 'ar' %} {{ item.media_location_ar }}
                                    {% elif LANGUAGE_CODE == 'de' %} {{ item.media_location_dr }}{% endif %}</li>
                                <li><i class="far fa-calendar"></i>{{item.date|date:'d M o'}}</li>
                            </ul>
                            <h3 class="title"><a href="{% url 'media:media_detail' item.id %}"> {% if LANGUAGE_CODE == 'en' %}{{ item.media_name }}
                                {% elif LANGUAGE_CODE == 'ar' %} {{ item.media_name_ar }}
                                {% elif LANGUAGE_CODE == 'de' %} {{ item.media_name_dr }}{% endif %}</a></h3>
                        </div>
                        <div class="media-caption-collapse">
                           
                            <div class="desc">
                                <p> {% if LANGUAGE_CODE == 'en' %}{{ item.media_desc1 }}
                                    {% elif LANGUAGE_CODE == 'ar' %} {{ item.media_desc1_ar }}
                                    {% elif LANGUAGE_CODE == 'de' %} {{ item.media_desc1_dr }}{% endif %}…</p>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
         
            {% endif %} {% endfor %}


        </div>
        <!-- media  End -->


        <div class="row max-mt-50">
            <div class="col text-center">
                <a href="{% url 'media:media' %}" class="btn btn-outline-primary load-more-btn">{% trans "Read More" %} <i
                        class="far fa-long-arrow-right ms-3"></i></a>
            </div>
        </div>

    </div>
</div>



{% endblock body %}

what_we_are_doing/templates/what-we-are-doing.html
{% extends 'base.html' %}
{% block body %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<div class="page-title-section section">
    <div class="page-title">

    </div>
    <div class="page-breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="{% url 'home:index' %}">{% trans "Home" %}</a></li>
        
                <li class="current">{% trans "What We Are Doing" %}</li>

            </ul>
        </div>
    </div>
</div>
<!-- Page Title Section End -->
<!-- page banner image Section Start -->
<div class="section  fix">
    <div class="container">
        <div class="row max-mb-n50">

            <div class="col-lg-12 col-12 order-lg-1 max-mb-50">
                <div class="row row-cols-1 g-0">

                    <div class=" col" data-aos="fade-up">

                        {% for item in data %}

                        <!-- Page Banner Section Start -->
                        <div class="page-banner-section section overlay section-padding"
                            data-bg-image="{{ item.image_bg_whatWeAreDoing}}">
                            <div class="container">
                                <div class="row">
                                    <div class="col-12">
                                        <div class="page-banner-title ashor-banner-title" style="padding: 50px;">

                                        </div>


                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}



                    </div>
                </div>
            </div>


        </div>
    </div>


</div>
<!-- page banner image Section Start -->


<!-- what we are doing Section Start -->
<div class="section" style="padding-top: 50px;">
    <div class="container">

        <!-- Section Title Start -->
        <div class="section-title" data-aos="fade-up">
            {% for item in data %}
            <p class="desc">       {% if LANGUAGE_CODE == 'en' %}{{item.text_WhatWeAreDoing}}
                {% elif LANGUAGE_CODE == 'ar' %}{{item.text_WhatWeAreDoing_ar}}
                {% elif LANGUAGE_CODE == 'de' %}{{item.text_WhatWeAreDoing_dr}}{% endif %}
            </p>
            {% endfor %}

        </div>
        <!-- Section Title End -->

        <!-- project Section Start --> 
        <div class="team-section section section-padding-bottom">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-7">
                        <div class="team-image-wrap">
                         
                            <div class="team-image">    {% for item in data %}
                                <img src="{{ item.image_bg_whatWeAreDoing_project}}" alt="team">
                                {% endfor %}
                            </div>
                           


                        </div>
                    </div>
                    <div class="col-lg-5">
                        <div class="about-content team-content mt-sm-50 mt-xs-50">
                            <h2 class="title">Ashor<span> {% trans "Project" %}</span> </h2>{% for item in data %}
                            <p>
                                {% if LANGUAGE_CODE == 'en' %}{{item.text_project}}
                                {% elif LANGUAGE_CODE == 'ar' %}{{item.text_project_ar}}
                                {% elif LANGUAGE_CODE == 'de' %}{{item.text_project_dr}}{% endif %}
         

                            </p>  {% endfor %}
                            <a href="{% url 'what_we_are_doing:project' %}" class="btn btn-primary btn-hover-secondary"> {% trans "LEARN MORE" %}</a>
                        </div>
                    </div>

                </div>
            </div>
        </div>                             

        <!-- project Section End -->


    </div>
</div>
<!-- About Event Section Start -->
<div class="about-section section">
    <div class="container">


        <div class="row">
            <div class="col-12">
                <div class="event-content">





                </div>
            </div>
        </div>
    </div>
</div>


<div class="teaching-section section section-padding-top section-padding-bottom-70" data-bg-color="#f5f5f5">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-xl-8">
                <div class="testimonial-area mb-md-50 mb-sm-30 mb-xs-30">
                    <div class="row">
                        
                        <div class="col-md-6">
                            <!-- Static Testimonial Start -->
                            <div class="static-testimonial">
                                <div class="testimonial-image">
                                    <div class="icon"><img class="svgInject"
                                            src="assets/images/svg/linea/linea-basic-flag2.svg" alt=""></div>
                                </div>
                                <div class="testimonial-content">
                                    <p>{% trans "A complex process of constructively changing relationships, attitudes,behaviours,interests and discourses in violence-prone conflict settings. Importantly,conflict." %}
                                    </p>
                                </div>
                                <div class="author-info">
                                    <div class="cite">
                                        <h6 class="name">{% trans "Economic Development and Resources Diversification" %}</h6>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="col-md-6 pr-100 pr-md-15 pr-sm-15 pr-xs-15">
                            <div class="testimonial-rating-area">
                                <div class="icon"><img class="svgInject"
                                        src="assets/images/svg/linea/linea-basic-flag2.svg" alt=""></div>

                                <div class="author-info" style="padding-top: 10px;">
                                    <div class="cite">
                                        <h6 class="name">{% trans "Gender Equality and Mainstreaming" %}
                                        </h6>
                                    </div>
                                </div>
                            </div>
                            <!-- Static Testimonial Start -->
                            <div class="static-testimonial">
                                <div class="icon"><img class="svgInject"
                                        src="assets/images/svg/linea/linea-basic-flag2.svg" alt=""></div>
                                <div class="testimonial-content">
                                    <p>{% trans "A complex process of constructively changing relationships, attitudes, behaviours, interests and discourses" %}
                                    </p>
                                </div>
                                <div class="author-info">
                                    <div class="cite">
                                        <h6 class="name">{% trans "Gender Equality" %}</h6>
                                    </div>
                                </div>
                            </div>
                            <!-- Static Testimonial End -->
                        </div>
                    </div>


                </div>
            </div>
            <div class="col-xl-4">
                <div class="teaching-content">
                    <!-- Section Title Start -->
                    <div class="section-title text-left mb-15" data-aos="fade-up">
                        <h2 class="title fz-48">Ashor <span> {% trans "Themes" %}</span></h2>
                    </div>
                    <!-- Section Title End -->{% for item in data %}
                    <p>
                        {% if LANGUAGE_CODE == 'en' %}{{item.text_themes}}
                        {% elif LANGUAGE_CODE == 'ar' %}{{item.text_themes_ar}}
                        {% elif LANGUAGE_CODE == 'de' %}{{item.text_themes_dr}}{% endif %}</p>{% endfor %}
                    <a href="{% url 'what_we_are_doing:themes' %}" class="btn btn-primary btn-hover-secondary mt-30">{% trans "READ MORE" %} </a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="section section-padding-bottom" style="padding-top: 50px;">
    <div class="container">

        <!--  media Bar Start -->
        <div class="row justify-content-between align-items-center max-mb-20">
            <div class="col-sm-auto col-12 max-mb-10">
                <p class="result-count">{% trans "Latest Media" %}</p>
            </div>

        </div>
        <!-- media Top Bar End -->

        <!-- media  Start -->
        <div class="row row-cols-xl-4 row-cols-lg-2 row-cols-md-2 row-cols-1 max-mb-n30">
            {% for item in media  %}
            {% if forloop.counter < 5 %} 
            <div class="col max-mb-30">
                <div class="media-6">
                    <div class="thumbnail">
                        <a class="image" href="{% url 'media:media_detail' item.id %}">
                            <img src="{{item.media_image.url}}" height="350px" style="object-fit: cover;" alt="">
                            <div class="media-overlay-bg"></div>
                        </a>
                    </div>
                    <div class="info">
                        <div class="media-caption-main">
                            <a class="category" style="color: white;"> {% if LANGUAGE_CODE == 'en' %}{{ item.category.en_name }}
                                {% elif LANGUAGE_CODE == 'ar' %} {{ item.category.ar_name }}
                                {% elif LANGUAGE_CODE == 'de' %} {{ item.category.dr_name }}{% endif %}</a>
                            <ul class="meta">
                                <li><i class="far fa-map-marker-alt"></i> {% if LANGUAGE_CODE == 'en' %}{{ item.media_location }}
                                    {% elif LANGUAGE_CODE == 'ar' %} {{ item.media_location_ar }}
                                    {% elif LANGUAGE_CODE == 'de' %} {{ item.media_location_dr }}{% endif %}</li>
                                <li><i class="far fa-calendar"></i>{{item.date|date:'d M o'}}</li>
                            </ul>
                            <h3 class="title"><a href="{% url 'media:media_detail' item.id %}"> {% if LANGUAGE_CODE == 'en' %}{{ item.media_name }}
                                {% elif LANGUAGE_CODE == 'ar' %} {{ item.media_name_ar }}
                                {% elif LANGUAGE_CODE == 'de' %} {{ item.media_name_dr }}{% endif %}</a></h3>
                        </div>
                        <div class="media-caption-collapse">
                           
                            <div class="desc">
                                <p> {% if LANGUAGE_CODE == 'en' %}{{ item.media_desc1 }}
                                    {% elif LANGUAGE_CODE == 'ar' %} {{ item.media_desc1_ar }}
                                    {% elif LANGUAGE_CODE == 'de' %} {{ item.media_desc1_dr }}{% endif %}…</p>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
         
            {% endif %} {% endfor %}


        </div>
        <!-- media  End -->


        <div class="row max-mt-50">
            <div class="col text-center">
                <a href="{% url 'media:media' %}" class="btn btn-outline-primary load-more-btn">{% trans "Read More" %} <i
                        class="far fa-long-arrow-right ms-3"></i></a>
            </div>
        </div>

    </div>
</div>

{% endblock body %}